# Adds the "Sponsor" button to the repository.
# Docs: https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
github: DevEmperor
custom: ['https://paypal.me/DevEmperor']
