version: '3'
services:
  android-dev:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - ~/.gradle:/root/.gradle:cached
    network_mode: "host" 
    command: sleep infinity
